# Generated by Django 5.1.2 on 2024-10-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnewsclustering', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='company',
            name='description2',
            field=models.TextField(default='Default Description'),
        ),
    ]
